layout:
  qmk_keyboard: corne_rotated
  layout_name: LAYOUT_split_3x5_3
layers:
  DEF:
    - [Q, W, F, P, B, J, L, U, Y, { "s": '"', "t": "'" }]
    - [
        { "t": "A", "h": "SUPER" },
        { "t": "R", "h": "ALT" },
        { "t": "S", "h": "CTRL" },
        { "t": "T", "h": "SHIFT" },
        G,
        M,
        { "t": "N", "h": "SHIFT" },
        { "t": "E", "h": "CTRL" },
        { "t": "I", "h": "ALT" },
        { "t": "O", "h": "SUPER" },
      ]
    - [
        Z,
        X,
        C,
        D,
        V,
        K,
        H,
        { "s": "<", "t": "," },
        { "s": ">", "t": "." },
        { "s": "?", "t": "/" },
      ]
    - { "t": "Esc", "h": "NAV" }
    - { "t": "Tab", "h": "NUM" }
    - { "t": "Enter", "h": "SYM" }
    - { "t": "Space", "h": "MOUSE" }
    - { "t": "Bksp", "h": "MEDIA" }
    - { "t": "Del" }
  NAV:
    - [null, null, null, null, null, "Undo", "Paste", "Copy", "Cut", "Redo"]
    - [SUPER, ALT, CTRL, SHIFT, Select All, H, J, K, L, Page Up]
    - [null, null, null, null, null, Left, Down, Up, Right, Page Down]
    - { type: held }
    - null
    - null
    - "Print\nScreen"
    - Home
    - End
  NUM:
    - [null, null, null, null, null, "(", 7, 8, 9, ")"]
    - [SUPER, ALT, CTRL, SHIFT, FUN, "+", 4, 5, 6, "*"]
    - [null, null, null, null, null, "-", 1, 2, 3, "/"]
    - null
    - { type: held }
    - null
    - "."
    - 0
    - ","
  FUN:
    - [null, null, null, null, null, F12, F7, F8, F9, null]
    - [null, null, null, null, { type: held }, F11, F4, F5, F6, null]
    - [null, null, null, null, null, F10, F1, F2, F3, null]
    - null
    - null
    - { type: held }
    - null
    - null
    - null
  SYM:
    - [
        null,
        null,
        null,
        null,
        null,
        { "s": "{", "t": "[" },
        "&",
        "*",
        "(",
        { "s": "}", "t": "]" },
      ]
    - [
        Super,
        Alt,
        Ctrl,
        Shift,
        null,
        { "s": "+", "t": "=" },
        "$",
        "%",
        "^",
        { "s": ":", "t": ";" },
      ]
    - [null, null, null, null, null, "-", "!", "@", "#", { "s": "~", "t": "`" }]
    - null
    - null
    - { type: held }
    - "_"
    - ")"
    - { "s": "|", "t": "\\" }
  MOUSE:
    - [
        null,
        "Mouse\nWheel\nLeft",
        "Mouse\nUp",
        "Mouse\nWheel\nRight",
        "Mouse\nWheel\nUp",
        null,
        null,
        null,
        null,
        null,
      ]
    - [
        null,
        "Mouse\nLeft",
        "Mouse\nDown",
        "Mouse\nRight",
        "Mouse\nWheel\nDown",
        null,
        SHIFT,
        CTRL,
        ALT,
        SUPER,
      ]
    - [null, null, null, null, null, null, null, null, null, null]
    - "Mouse\n3"
    - "Mouse\n2"
    - "Mouse\n1"
    - { type: held }
    - null
    - null
  MEDIA:
    - [
        null,
        "Bright.\nDown",
        "Bright.\nUp",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ]
    - [
        "Media\nPrev",
        "Vol -",
        "Vol +",
        "Media\nNext",
        null,
        null,
        null,
        null,
        null,
        null,
      ]
    - [null, null, null, null, null, null, null, null, null, null]
    - "Media\nStop"
    - "Media\nPlay"
    - Mute
    - null
    - { type: held }
    - null
